# UCS420 – Cognitive Computing
## Assignment 3 | Pandas Practice

**Student:** Parth Khurana  
**Roll Number:** 1024170354  
**Batch:** 3Q33

In [1]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

## Q1 — Building the required DataFrame

First, I have entered the values from the question into Python lists and then combined them into one Pandas DataFrame. Keeping the data in a dictionary makes the column structure easy to read.

In [2]:
records = [
    [1, "Yes", "Single", "125K", "No"],
    [2, "No", "Married", "100K", "No"],
    [3, "No", "Single", "70K", "No"],
    [4, "Yes", "Married", "120K", "No"],
    [5, "No", "Divorced", "95K", "Yes"],
    [6, "No", "Married", "60K", "No"],
    [7, "Yes", "Divorced", "220K", "No"],
    [8, "No", "Single", "85K", "Yes"],
    [9, "No", "Married", "75K", "No"],
    [10, "No", "Single", "90K", "Yes"]
]

columns = ["Tid", "Refund", "Marital Status", "Taxable Income", "Cheat"]
df = pd.DataFrame(records, columns=columns)

display(df)

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

## Q2 — Selecting specific rows

The required rows are selected with `loc`. Since the DataFrame keeps the default integer labels, the requested labels can be passed together as a list.

In [3]:
selected_rows = df.loc[[0, 4, 7, 8]]
display(selected_rows)

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

## Q3 — Working with `iloc`

Here I use positional indexing. The ending position in an `iloc` slice is not included, so the stop values are one position beyond the last row or column wanted.

In [4]:
print("1) Rows 3 through 7")
display(df.iloc[3:8])

print("2) Rows 4 through 8, columns 2 through 4")
display(df.iloc[4:9, 2:5])

print("3) Every row, columns 1 through 3")
display(df.iloc[:, 1:4])

1. Rows from index 3 to 7:

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

2. Rows from index 4 to 8 and columns 2 to 4:

  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

3. All rows with column index 1 to 3:

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

## Q4 — Loading and previewing the Iris CSV

The Iris dataset is read with `read_csv()` and the first five records are displayed. If the CSV is missing, the notebook tries to obtain the Kaggle copy automatically.

In [5]:
from pathlib import Path
import urllib.request
import zipfile

iris_path = Path("Iris.csv")

if not iris_path.is_file():
    download_url = "https://www.kaggle.com/api/v1/datasets/download/uciml/iris"
    archive = Path("iris_dataset.zip")

    try:
        urllib.request.urlretrieve(download_url, archive)
        with zipfile.ZipFile(archive) as zf:
            zf.extractall(".")
        print("Iris CSV downloaded.")
    except Exception as err:
        print("Automatic download failed:", err)

iris_df = pd.read_csv(iris_path)
print("First five records:")
display(iris_df.iloc[:5])

First five rows of Iris dataset:

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0   1            5.1           3.5            1.4           0.2  setosa
1   2            4.9           3.0            1.4           0.2  setosa
2   3            4.7           3.2            1.3           0.2  setosa
3   4            4.6           3.1            1.5           0.2  setosa
4   5            5.0           3.6            1.4           0.2  setosa

## Q5 — Removing a row and a column

For this question, row 4 and column 3 are treated as zero-based positions. The row is removed first, followed by the fourth column.

In [6]:
iris_modified = iris_df.drop(index=4).copy()

removed_column = iris_modified.columns[3]
iris_modified.drop(columns=removed_column, inplace=True)

print("Removed row:", 4)
print("Removed column:", removed_column)
display(iris_modified.head(10))

Deleted row index: 4
Deleted column index: 3 -> PetalLengthCm

    Id  SepalLengthCm  SepalWidthCm  PetalWidthCm Species
0    1            5.1           3.5           0.2  setosa
1    2            4.9           3.0           0.2  setosa
2    3            4.7           3.2           0.2  setosa
3    4            4.6           3.1           0.2  setosa
5    6            5.4           3.9           0.4  setosa
6    7            4.6           3.4           0.3  setosa
7    8            5.0           3.4           0.2  setosa
8    9            4.4           2.9           0.2  setosa
9   10            4.9           3.1           0.1  setosa
10  11            5.4           3.7           0.2  setosa

# Q6 — Employee DataFrame

The employee information from the question is stored in a dictionary, converted into a DataFrame, and also written to `employees.csv` for the later operations.

In [7]:
employee_data = [
    [101, "Alice", "HR", 29, 50000, 4, "2020-03-15", "Female", 5000, 4.5],
    [102, "Bob", "IT", 34, 70000, 8, "2017-07-19", "Male", 7000, 4.0],
    [103, "Charlie", "IT", 41, 65000, 10, "2013-06-01", "Male", 6000, 3.8],
    [104, "Diana", "Marketing", 28, 55000, 3, "2021-02-10", "Female", 4500, 4.7],
    [105, "Edward", "Sales", 38, 60000, 12, "2010-11-25", "Male", 5000, 3.5]
]

employee_columns = [
    "Employee_ID", "Name", "Department", "Age", "Salary",
    "Years_of_Experience", "Joining_Date", "Gender", "Bonus", "Rating"
]

employees_df = pd.DataFrame(employee_data, columns=employee_columns)
employees_df["Joining_Date"] = pd.to_datetime(employees_df["Joining_Date"])

employees_df.to_csv("employees.csv", index=False)

print("employees.csv has been created.")
display(employees_df)

employees.csv created successfully.

   Employee_ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  Gender  Bonus  Rating
0          101    Alice         HR   29   50000                    4   2020-03-15  Female   5000     4.5
1          102      Bob         IT   34   70000                    8   2017-07-19    Male   7000     4.0
2          103  Charlie         IT   41   65000                   10   2013-06-01    Male   6000     3.8
3          104    Diana  Marketing   28   55000                    3   2021-02-10  Female   4500     4.7
4          105   Edward      Sales   38   60000                   12   2010-11-25    Male   5000     3.5

## Q6(a) — DataFrame dimensions

The `shape` attribute reports the number of rows followed by the number of columns.

In [8]:
rows, columns = employees_df.shape
print(f"Rows: {rows}")
print(f"Columns: {columns}")

Shape: (5, 10)

## Q6(b) — Inspecting the DataFrame

`info()` is useful for checking column names, data types, and whether any values are missing.

In [9]:
employees_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      datetime64[ns]
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(5), object(3)
memory usage: 532.0+ bytes

## Q6(c) — Numerical summary

For numerical fields, `describe()` provides the main descriptive statistics such as mean, quartiles, minimum, and maximum.

In [10]:
summary = employees_df.describe()
display(summary)

       Employee_ID        Age       Salary  Years_of_Experience         Joining_Date   Bonus    Rating
count     5.000000   5.000000      5.00000             5.000000                    5     5.0  5.000000
mean    103.000000  34.000000  60000.00000             7.400000  2016-08-20 00:00:00  5500.0  4.100000
min     101.000000  28.000000  50000.00000             3.000000  2010-11-25 00:00:00  4500.0  3.500000
25%     102.000000  29.000000  55000.00000             4.000000  2013-06-01 00:00:00  5000.0  3.800000
50%     103.000000  34.000000  60000.00000             8.000000  2017-07-19 00:00:00  5000.0  4.000000
75%     104.000000  38.000000  65000.00000            10.000000  2020-03-15 00:00:00  6000.0  4.500000
max     105.000000  41.000000  70000.00000            12.000000  2021-02-10 00:00:00  7000.0  4.700000
std       1.581139   5.612486   7905.69415             3.847077                  NaN  1000.0  0.494975

## Q6(d) — Preview the beginning and end

I use `head(5)` for the first five records and `tail(3)` for the final three records.

In [11]:
print("First five employees:")
display(employees_df.head())

print("Last three employees:")
display(employees_df.tail(3))

First 5 rows:

   Employee_ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  Gender  Bonus  Rating
0          101    Alice         HR   29   50000                    4   2020-03-15  Female   5000     4.5
1          102      Bob         IT   34   70000                    8   2017-07-19    Male   7000     4.0
2          103  Charlie         IT   41   65000                   10   2013-06-01    Male   6000     3.8
3          104    Diana  Marketing   28   55000                    3   2021-02-10  Female   4500     4.7
4          105   Edward      Sales   38   60000                   12   2010-11-25    Male   5000     3.5

Last 3 rows:

   Employee_ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  Gender  Bonus  Rating
2          103  Charlie         IT   41   65000                   10   2013-06-01    Male   6000     3.8
3          104    Diana  Marketing   28   55000                    3   2021-02-10  Female   4500     4.7
4          105   Edward      Sales   38   60000                   12   2010-11-25    Male   5000     3.5

## Q6(e) — Calculating the requested values

The following expressions calculate the average salary, total bonus, minimum age, and maximum rating directly from their respective columns.

In [12]:
avg_salary = employees_df["Salary"].mean()
bonus_total = employees_df["Bonus"].sum()
min_age = employees_df["Age"].min()
top_rating = employees_df["Rating"].max()

print(f"1. Average salary: ₹{avg_salary:,.2f}")
print(f"2. Total bonus: ₹{bonus_total:,.2f}")
print(f"3. Youngest age: {min_age}")
print(f"4. Highest rating: {top_rating}")

i. Average salary: ₹60,000.00
ii. Total bonus paid: ₹27,500.00
iii. Youngest employee's age: 28
iv. Highest performance rating: 4.7

## Q6(f) — Salary ranking

Sorting the salary column in descending order places the highest-paid employee at the top.

In [13]:
salary_order = employees_df.sort_values(
    "Salary",
    ascending=False
)
display(salary_order)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  Gender  Bonus  Rating
1          102      Bob         IT   34   70000                    8   2017-07-19    Male   7000     4.0
2          103  Charlie         IT   41   65000                   10   2013-06-01    Male   6000     3.8
4          105   Edward      Sales   38   60000                   12   2010-11-25    Male   5000     3.5
3          104    Diana  Marketing   28   55000                    3   2021-02-10  Female   4500     4.7
0          101    Alice         HR   29   50000                    4   2020-03-15  Female   5000     4.5

## Q6(g) — Converting ratings into categories

A small function maps each rating to the category specified in the question. The result is stored in a new column.

In [14]:
def classify_rating(value):
    if value >= 4.5:
        return "Excellent"
    if value >= 4.0:
        return "Good"
    return "Average"

employees_df["Performance_Category"] = employees_df["Rating"].map(classify_rating)
display(employees_df)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

## Q6(h) — Checking for missing entries

`isnull().sum()` gives a column-wise count of missing values.

In [15]:
null_counts = employees_df.isna().sum()
print("Missing values by column:")
display(null_counts)

Missing values in each column:

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

## Q6(i) — Renaming the employee identifier

The `Employee_ID` column is renamed to the shorter label `ID`.

In [16]:
employees_df.rename(
    columns={"Employee_ID": "ID"},
    inplace=True
)
display(employees_df)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  Gender  Bonus  Rating Performance_Category
0  101    Alice         HR   29   50000                    4   2020-03-15  Female   5000     4.5            Excellent
1  102      Bob         IT   34   70000                    8   2017-07-19    Male   7000     4.0                 Good
2  103  Charlie         IT   41   65000                   10   2013-06-01    Male   6000     3.8              Average
3  104    Diana  Marketing   28   55000                    3   2021-02-10  Female   4500     4.7            Excellent
4  105   Edward      Sales   38   60000                   12   2010-11-25    Male   5000     3.5              Average

## Q6(j) — Filtering employee records

Two filters are applied separately: one for experience greater than five years and another for employees in the IT department.

In [17]:
experienced = employees_df.query("Years_of_Experience > 5")
it_team = employees_df.loc[employees_df["Department"].eq("IT")]

print("Employees with more than 5 years of experience:")
display(experienced)

print("Employees working in IT:")
display(it_team)

i. Employees with more than 5 years of experience:

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date Gender  Bonus  Rating Performance_Category
1  102      Bob         IT   34   70000                    8   2017-07-19   Male   7000     4.0                 Good
2  103  Charlie         IT   41   65000                   10   2013-06-01   Male   6000     3.8              Average
4  105   Edward      Sales   38   60000                   12   2010-11-25   Male   5000     3.5              Average

ii. Employees belonging to the IT department:

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date Gender  Bonus  Rating Performance_Category
1  102      Bob         IT   34   70000                    8   2017-07-19   Male   7000     4.0                 Good
2  103  Charlie         IT   41   65000                   10   2013-06-01   Male   6000     3.8              Average

## Q6(k) — Computing employee tax

The tax column is calculated from salary using the 10% rate given in the question.

In [18]:
employees_df["Tax"] = employees_df["Salary"].mul(0.10)
display(employees_df)

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

## Q6(l) — Exporting the final DataFrame

Finally, the updated DataFrame is saved as `employees_modified.csv` and read back once to confirm the saved file.

In [19]:
save_path = "employees_modified.csv"
employees_df.to_csv(save_path, index=False)

print(f"Saved updated employee data to {save_path}")
display(pd.read_csv(save_path))

Modified DataFrame saved successfully as: employees_modified.csv

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0